const fs = require('fs');
const path = require('path');
// ...existing code...
const { execSync } = require('child_process');
// ...existing code...
const readline = require('readline');
// ...existing code...
module.exports = {
  // ...existing code...
};
